apiVersion: v1
kind: Pod
metadata:
  name: mc
  namespace: nginx-test
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: registry.cn-shanghai.aliyuncs.com/ys1000/nginx:latest
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: registry.cn-shanghai.aliyuncs.com/ys1000/debian:latest
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 10;
        done
